### ISSUE TITLE
Complete README.md

### ISSUE THREAD

**Issue by gmacario** [gmacario/colorcode#1]
- [X] Brainstorm about your target user (https://github.com/gmacario/colorcode/issues/3)
- [X] Gather information needed by the target user (https://github.com/gmacario/colorcode/issues/4)
- [X] Pick an idea (https://github.com/gmacario/colorcode/issues/5)
  - [X] Write the (five) functions which the app will implement
- [X] Design a solution (https://github.com/gmacario/colorcode/issues/6)

**Comment by gmacario** [comment]
Partial fix via 8a865f153bc20307fd1865f7a3276f1b7aa9b1e9

**Comment by gmacario** [comment]
All subtasks completed, closing issue.
